/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVXNlci9Eb2N1bWVudHMvUHJvamVjdHMvbWVhbiBzdGFjay9KIGFuZCBWZSB3ZWRkaW5nL3dlZGRpbmcgYXBwIHYxL2Fzc2V0cy9hcHAvcnN2cC9yc3ZwLWluZm8uY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9Vc2VyL0RvY3VtZW50cy9Qcm9qZWN0cy9tZWFuIHN0YWNrL0ogYW5kIFZlIHdlZGRpbmcvd2VkZGluZyBhcHAgdjEvYXNzZXRzL2FwcC9yc3ZwL3JzdnAtaW5mby5jb21wb25lbnQuY3NzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7OzsifQ==
