/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvVXNlci9Eb2N1bWVudHMvUHJvamVjdHMvbWVhbiBzdGFjay9KIGFuZCBWZSB3ZWRkaW5nL3dlZGRpbmcgYXBwIHYxL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5jc3Muc2hpbS5uZ3N0eWxlLnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvVXNlci9Eb2N1bWVudHMvUHJvamVjdHMvbWVhbiBzdGFjay9KIGFuZCBWZSB3ZWRkaW5nL3dlZGRpbmcgYXBwIHYxL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
